image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG_BASE: "$CI_REGISTRY/sid/daikon-backend"

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - push

.build_template: &build_template
  stage: build
  script:
    - docker build -t ${IMAGE_TAG_BASE}-${SERVICE}:$CI_COMMIT_REF_NAME -f ${DOCKERFILE} .
  only:
    - lab-main

.push_template: &push_template
  stage: push
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push ${IMAGE_TAG_BASE}-${SERVICE}:$CI_COMMIT_REF_NAME
  only:
    - lab-main

build_and_push:
  parallel:
    matrix:
      - SERVICE: "userstore-api"
        DOCKERFILE: "src/Identities/UserStore/UserStore.API/Dockerfile"
      - SERVICE: "gene-api"
        DOCKERFILE: "src/Services/Gene/Gene.API/Dockerfile"
      - SERVICE: "target-api"
        DOCKERFILE: "src/Services/Target/Target.API/Dockerfile"
      - SERVICE: "screen-api"
        DOCKERFILE: "src/Services/Screen/Screen.API/Dockerfile"
      - SERVICE: "hitassessment-api"
        DOCKERFILE: "src/Services/HitAssessment/HitAssessment.API/Dockerfile"
      - SERVICE: "project-api"
        DOCKERFILE: "src/Services/Project/Project.API/Dockerfile"
      - SERVICE: "horizon-api"
        DOCKERFILE: "src/Services/Horizon/Horizon.API/Dockerfile"
      - SERVICE: "mlogix-api"
        DOCKERFILE: "src/Services/MLogix/MLogix.API/Dockerfile"
      - SERVICE: "moldb-api"
        DOCKERFILE: "src/Services/Chem/MolDb.API/Dockerfile"
      - SERVICE: "questionnaire-api"
        DOCKERFILE: "src/Services/Questionnaire/Questionnaire.API/Dockerfile"
      - SERVICE: "comment-api"
        DOCKERFILE: "src/Services/Comment/Comment.API/Dockerfile"
      - SERVICE: "simplegw-api"
        DOCKERFILE: "src/ApiGateways/SimpleGW/SimpleGW.API/Dockerfile"

  include:
    - job: build
      <<: *build_template

    - job: push
      <<: *push_template
