services:
  DKPortainer:
    image: portainer/portainer
    container_name: dk_portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - amr_portainer_data:/data
    networks:
      - daikon-be-net

  DKPGAdmin:
    image: dpage/pgadmin4
    container_name: dk_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - amr_pgadmin_data:/root/.pgadmin
    networks:
      - daikon-be-net

  Kafka:
    container_name: "kafka"
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "amr_kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@Kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - daikon-be-net

  EventStoreDb:
    container_name: "eventstoredb"
    image: mongo:jammy
    restart: always
    cpus: '0.1'
    ports:
      - "27017:27017"
    volumes:
      - "amr_eventdb_mongo_data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - daikon-be-net

  Neo4j:
    image: neo4j:5.25-community
    container_name: dk_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - amr_neo4j_data:/data
      - amr_neo4j_import:/var/lib/neo4j/import
      # - amr_neo4j_logs:/logs
      # - amr_neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

    networks:
      - daikon-be-net

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 5051:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: Kafka:9092
    networks:
      - daikon-be-net

volumes:
  amr_portainer_data:
  amr_pgadmin_data:
  amr_eventdb_mongo_data:
  amr_kafka_data:
  amr_neo4j_data:
  amr_neo4j_import:
  amr_neo4j_logs:
  amr_neo4j_plugins:

networks:
  daikon-be-net:
    external: true
    name: daikon-be-net