
services:
  Gene.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "GeneMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "GeneMongoDbSettings:DatabaseName=Gene"

      - "GeneMongoDbSettings:GeneCollectionName=Genes"
      - "GeneMongoDbSettings:StrainCollectionName=Strains"
      - "GeneMongoDbSettings:GeneEssentialityCollectionName=Essentialities"
      - "GeneMongoDbSettings:GeneProteinProductionCollectionName=ProteinProductions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayCollectionName=ProteinActivityAssays"
      - "GeneMongoDbSettings:GeneHypomorphCollectionName=Hypomorphs"
      - "GeneMongoDbSettings:GeneCrispriStrainCollectionName=CrispriStrains"
      - "GeneMongoDbSettings:GeneResistanceMutationCollectionName=ResistanceMutations"
      - "GeneMongoDbSettings:GeneVulnerabilityCollectionName=Vulnerabilities"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationCollectionName=UnpublishedStructuralInformations"
      - "GeneMongoDbSettings:GeneExpansionPropCollectionName=GeneExpansionProps"

      - "GeneMongoDbSettings:GeneRevisionCollectionName=GenesRevisions"
      - "GeneMongoDbSettings:StrainRevisionCollectionName=StrainsRevisions"
      - "GeneMongoDbSettings:GeneEssentialityRevisionCollectionName=EssentialitiesRevisions"
      - "GeneMongoDbSettings:GeneProteinProductionRevisionCollectionName=ProteinProductionsRevisions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayRevisionCollectionName=ProteinActivityAssaysRevisions"
      - "GeneMongoDbSettings:GeneHypomorphRevisionCollectionName=HypomorphsRevisions"
      - "GeneMongoDbSettings:GeneCrispriStrainRevisionCollectionName=CrispriStrainsRevisions"
      - "GeneMongoDbSettings:GeneResistanceMutationRevisionCollectionName=ResistanceMutationsRevisions"
      - "GeneMongoDbSettings:GeneVulnerabilityRevisionCollectionName=VulnerabilitiesRevisions"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationRevisionCollectionName=UnpublishedStructuralInformationsRevisions"
      - "GeneMongoDbSettings:ExpansionPropRevisionCollectionName=GeneExpansionPropsRevisions"



      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8001:80"

  Target.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "TargetMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "TargetMongoDbSettings:DatabaseName=Target"

      - "TargetMongoDbSettings:TargetCollectionName=Targets"
      - "TargetMongoDbSettings:PromotionResponseCollectionName=PromotionResponses"

      - "TargetMongoDbSettings:TargetRevisionCollectionName=TargetsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=target-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8002:80"

  Screen.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "ScreenMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "ScreenMongoDbSettings:DatabaseName=Screen"

      - "ScreenMongoDbSettings:ScreenCollectionName=Screens"
      - "ScreenMongoDbSettings:ScreenRunCollectionName=ScreenRuns"
      - "ScreenMongoDbSettings:HitCollectionCollectionName=HitCollections"
      - "ScreenMongoDbSettings:HitCollectionName=Hits"

      - "ScreenMongoDbSettings:ScreenRevisionCollectionName=ScreensRevisions"
      - "ScreenMongoDbSettings:ScreenRunRevisionCollectionName=ScreenRunsRevisions"
      - "ScreenMongoDbSettings:HitCollectionRevisionCollectionName=HitCollectionsRevisions"
      - "ScreenMongoDbSettings:HitRevisionCollectionName=HitRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=screen-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8003:80"

  HitAssessment.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "HAMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "HAMongoDbSettings:DatabaseName=HitAssessment"

      - "HAMongoDbSettings:HitAssessmentCollectionName=HitAssessments"
      - "HAMongoDbSettings:HaCompoundEvolutionCollectionName=HaCompoundEvolutions"

      - "HAMongoDbSettings:HitAssessmentRevisionCollectionName=HitAssessmentsRevisions"
      - "HAMongoDbSettings:HaCompoundEvolutionRevisionCollectionName=HaCompoundEvolutionsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=hitassessment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8004:80"

  Project.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "ProjectMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "ProjectMongoDbSettings:DatabaseName=Project"

      - "ProjectMongoDbSettings:ProjectCollectionName=Projects"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionCollectionName=ProjectCompoundEvolutions"

      - "ProjectMongoDbSettings:ProjectRevisionCollectionName=ProjectsRevisions"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionRevisionCollectionName=ProjectCompoundEvolutionsRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=project-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8005:80"


  Horizon.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "HorizonNeo4jSettings:Uri=bolt://neo4j:7687"
      - "HorizonNeo4jSettings:User=neo4j"
      - "HorizonNeo4jSettings:Password=1k5SPVHJ4FZ9"
      - "HorizonNeo4jSettings:Database=horizon"


      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=horizon-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8006:80"

  MLogix.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "EventDatabaseSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      - "KafkaProducerSettings:BootstrapServers=Kafka:9092"
      - "KafkaProducerSettings:Topic=daikon-core-events"

      - "MLxMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "MLxMongoDbSettings:DatabaseName=MoleculeLogix"

      - "MLxMongoDbSettings:MoleculeCollectionName=Molecules"
      - "MLxMongoDbSettings:MoleculeRevisionCollectionName=MoleculesRevisions"

      - "KafkaConsumerSettings:BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings:Topics=daikon-core-events"
      - "KafkaConsumerSettings:GroupId=mlogix-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"

    ports:
      - "8007:80"

  

  UserStore.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "UserStoreMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "UserStoreMongoDbSettings:DatabaseName=UserStore"

      - "UserStoreMongoDbSettings:AppOrgCollectionName=AppOrgs"
      - "UserStoreMongoDbSettings:AppUserCollectionName=AppUsers"
      - "UserStoreMongoDbSettings:AppRoleCollectionName=AppRoles"
      - "UserStoreMongoDbSettings:APIResourceCollectionName=AppAPIResources"
    ports:
      - "8011:80"

  # Ocelotapigw:
  #   container_name: ocelotapigw
  #   environment:
  #     - "ASPNETCORE_ENVIRONMENT=Cluster"
  #     - ASPNETCORE_URLS=http://+:80
  #     - "UserStoreAPI:BaseUrl=http://UserStore.API/api/v2/"
  #   ports:
  #     - "8010:80"

  SimpleGW.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      -  OIDCProvider=EntraID
      -  EntraID:Instance=${EntraID_Instance}
      -  EntraID:Domain=${EntraID_Domain}
      -  EntraID:TenantId=${EntraID_TenantId}
      -  EntraID:ClientId=${EntraID_ClientId}
      -  EntraID:Audience=${EntraID_Audience}

      - "UserStoreAPI:BaseUrl=http://UserStore.API/api/v2/"

      - "EndPointRouting:gene=http://Gene.API"
      - "EndPointRouting:gene-batch=http://Gene.API"
      - "EndPointRouting:strain=http://Gene.API"

      - "EndPointRouting:target=http://Target.API"
      - "EndPointRouting:screen=http://Screen.API"
      - "EndPointRouting:hit-collection=http://Screen.API"

      - "EndPointRouting:hit-assessment=http://HitAssessment.API"
      - "EndPointRouting:project=http://Project.API"
      - "EndPointRouting:horizon=http://Horizon.API"
      - "EndPointRouting:molecule=http://MLogix.API"
      - "EndPointRouting:api-resources=http://UserStore.API"
      - "EndPointRouting:app-settings=http://UserStore.API"
      - "EndPointRouting:org=http://UserStore.API"
      - "EndPointRouting:roles=http://UserStore.API"
      - "EndPointRouting:user=http://UserStore.API"
      - "EndPointRouting:questionnaire=http://Questionnaire.API"
      - "EndPointRouting:mol-db=http://MolDb.API"

      
    ports:
      - "8010:80"


  MolDb.API:
    environment:
      - "KafkaConsumerSettings_BootstrapServers=Kafka:9092"
      - "KafkaConsumerSettings_Topics=daikon-core-events"
      - "KafkaConsumerSettings_GroupId=moldb-consumer-group"
      - "KafkaConsumerSettings_AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings_EnableAutoCommit=true"
      - "KafkaConsumerSettings_AllowAutoCreateTopics=true"
    ports:
      - "8101:80"


  Questionnaire.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - "QuestionnaireMongoDbSettings:ConnectionString=mongodb://admin:password@EventStoreDb:27017"
      - "QuestionnaireMongoDbSettings:DatabaseName=Project"

    ports:
      - "8008:80"
