services:
  simplegw-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## OIDC
      - OIDCProvider=EntraID
      - EntraID:Instance=${EntraID_Instance}
      - EntraID:Domain=${EntraID_Domain}
      - EntraID:TenantId=${EntraID_TenantId}
      - EntraID:ClientId=${EntraID_ClientId}
      - EntraID:Audience=${EntraID_Audience}

      ## OIDC
      # - OIDCProvider=KeyCloak
      # - KeyCloak:Instance=${Keycloak_Instance}
      # - KeyCloak:TenantId=${Keycloak_Realm}
      # - KeyCloak:ClientId=${Keycloak_ClientId}
      # - KeyCloak:Audience=${Keycloak_Audience}
      # - KeyCloak:Authority=${Keycloak_Authority}

      ## Internal API Routing
      - "UserStoreAPI:BaseUrl=http://userstore-api/api/v2/"

      - "EndPointRouting:gene=http://gene-api"
      - "EndPointRouting:gene-batch=http://gene-api"
      - "EndPointRouting:strain=http://gene-api"

      - "EndPointRouting:target=http://target-api"
      - "EndPointRouting:screen=http://screen-api"
      - "EndPointRouting:hit-collection=http://screen-api"

      - "EndPointRouting:hit-assessment=http://hitassessment-api"
      - "EndPointRouting:project=http://project-api"
      - "EndPointRouting:horizon=http://horizon-api"
      - "EndPointRouting:molecule=http://mlogix-api"
      - "EndPointRouting:api-resources=http://userstore-api"
      - "EndPointRouting:app-settings=http://userstore-api"
      - "EndPointRouting:org=http://userstore-api"
      - "EndPointRouting:roles=http://userstore-api"
      - "EndPointRouting:user=http://userstore-api"
      - "EndPointRouting:questionnaire=http://questionnaire-api"
      - "EndPointRouting:comment=http://comment-api"
      - "EndPointRouting:docu-store=http://docustore-api"

      - "EndPointRouting:event-history=http://event-history-api"

    ports:
      - "8010:80"
    networks:
      - daikon-be-net
  


  userstore-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## MongoDb Data Store
      - UserStoreMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "UserStoreMongoDbSettings:DatabaseName=UserStore"

      - "UserStoreMongoDbSettings:AppOrgCollectionName=AppOrgs"
      - "UserStoreMongoDbSettings:AppUserCollectionName=AppUsers"
      - "UserStoreMongoDbSettings:AppRoleCollectionName=AppRoles"
      - "UserStoreMongoDbSettings:APIResourceCollectionName=AppAPIResources"
    ports:
      - "8011:80"
    networks:
      - daikon-be-net

  gene-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}

      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - GeneMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "GeneMongoDbSettings:DatabaseName=Gene"
      - "GeneMongoDbSettings:GeneCollectionName=Genes"
      - "GeneMongoDbSettings:StrainCollectionName=Strains"
      - "GeneMongoDbSettings:GeneEssentialityCollectionName=Essentialities"
      - "GeneMongoDbSettings:GeneProteinProductionCollectionName=ProteinProductions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayCollectionName=ProteinActivityAssays"
      - "GeneMongoDbSettings:GeneHypomorphCollectionName=Hypomorphs"
      - "GeneMongoDbSettings:GeneCrispriStrainCollectionName=CrispriStrains"
      - "GeneMongoDbSettings:GeneResistanceMutationCollectionName=ResistanceMutations"
      - "GeneMongoDbSettings:GeneVulnerabilityCollectionName=Vulnerabilities"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationCollectionName=UnpublishedStructuralInformations"
      - "GeneMongoDbSettings:GeneExpansionPropCollectionName=GeneExpansionProps"

    ports:
      - "8001:80"

    networks:
      - daikon-be-net

  target-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

        ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=target-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - TargetMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "TargetMongoDbSettings:DatabaseName=Target"

      - "TargetMongoDbSettings:TargetCollectionName=Targets"
      - "TargetMongoDbSettings:PromotionResponseCollectionName=PromotionResponses"
      - "TargetMongoDbSettings:TargetToxicologyCollectionName=TargetToxicologies"

    ports:
      - "8002:80"

    networks:
      - daikon-be-net

  screen-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}

      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=screen-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - ScreenMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "ScreenMongoDbSettings:DatabaseName=Screen"

      - "ScreenMongoDbSettings:ScreenCollectionName=Screens"
      - "ScreenMongoDbSettings:ScreenRunCollectionName=ScreenRuns"
      - "ScreenMongoDbSettings:HitCollectionCollectionName=HitCollections"
      - "ScreenMongoDbSettings:HitCollectionName=Hits"

      ## Internal APIs
      - "MolDbAPI:Url=http://moldb-api/api/v2/mol-db"
      - "MLogixAPI:Url=http://mlogix-api/api/v2"

    ports:
      - "8003:80"
    networks:
      - daikon-be-net

  hitassessment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=hitassessment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - HAMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "HAMongoDbSettings:DatabaseName=HitAssessment"

      - "HAMongoDbSettings:HitAssessmentCollectionName=HitAssessments"
      - "HAMongoDbSettings:HaCompoundEvolutionCollectionName=HaCompoundEvolutions"


      ## Internal APIs
      - "MolDbAPI:Url=http://moldb-api/api/v2/mol-db"
      - "MLogixAPI:Url=http://mlogix-api/api/v2"

    ports:
      - "8004:80"
    networks:
      - daikon-be-net

  project-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=project-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - ProjectMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "ProjectMongoDbSettings:DatabaseName=Project"

      - "ProjectMongoDbSettings:ProjectCollectionName=Projects"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionCollectionName=ProjectCompoundEvolutions"

      ## Internal APIs
      - "MolDbAPI:Url=http://moldb-api/api/v2/mol-db"
      - "MLogixAPI:Url=http://mlogix-api/api/v2"

    ports:
      - "8005:80"
    networks:
      - daikon-be-net

  horizon-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      # Neo4j
      - HorizonNeo4jSettings:Uri=${HorizonNeo4jURI}
      - HorizonNeo4jSettings:User=${HorizonNeo4jUser}
      - HorizonNeo4jSettings:Password=${HorizonNeo4jPassword}
      - "HorizonNeo4jSettings:Database=neo4j"

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=horizon-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8006:80"
    networks:
      - daikon-be-net

  mlogix-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      # Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      # Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      # Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=mlogix-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      # MongoDb Data Store
      - MLxMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "MLxMongoDbSettings:DatabaseName=MoleculeLogix"
      - "MLxMongoDbSettings:MoleculeCollectionName=Molecules"


      # Internal APIs
      - "MolDbAPI:Url=http://moldb-api:8101/api/v2/mol-db"
      - "DaikonChemVault:Url=http://daikon_chem_vault_api:10001"

    ports:
      - "8007:80"
    networks:
      - daikon-be-net

  questionnaire-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Data Store
      - QuestionnaireMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "QuestionnaireMongoDbSettings:DatabaseName=Questionnaire"

    ports:
      - "8008:80"
    networks:
      - daikon-be-net

  comment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=comment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - CommentMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "CommentMongoDbSettings:DatabaseName=Comments"

      - "CommentMongoDbSettings:CommentCollectionName=Comments"
      - "CommentMongoDbSettings:CommentReplyCollectionName=CommentReplies"


      ## Internal APIs
      - "MolDbAPI:Url=http://moldb-api/api/v2/mol-db"
      - "MLogixAPI:Url=http://mlogix-api/api/v2"

    ports:
      - "8009:80"
    networks:
      - daikon-be-net

  event-history-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"
      - "UserStoreAPI:Url=http://userstore-api/api/v2"
      - "GeneAPI:Url=http://gene-api/api/v2"
      - "TargetAPI:Url=http://target-api/api/v2"
      - "ScreenAPI:Url=http://screen-api/api/v2"
      - "HitAssessmentAPI:Url=http://hitassessment-api/api/v2"
      - "ProjectAPI:Url=http://project-api/api/v2"

    ports:
      - "8012:80"
    networks:
      - daikon-be-net

  docustore-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=docustore-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - DocuStoreMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "DocuStoreMongoDbSettings:DatabaseName=DocuStore"

      - "DocuStoreMongoDbSettings:ParsedDocCollectionName=ParsedDocs"
      ## Internal APIs
      - "MLogixAPI:Url=http://mlogix-api/api/v2"

    ports:
      - "8014:80"
    networks:
      - daikon-be-net

  

networks:
  daikon-be-net:
    name: daikon-be-net
    external: true
