services:
  Gene.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}

      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=gene-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - GeneMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "GeneMongoDbSettings:DatabaseName=Gene"
      - "GeneMongoDbSettings:GeneCollectionName=Genes"
      - "GeneMongoDbSettings:StrainCollectionName=Strains"
      - "GeneMongoDbSettings:GeneEssentialityCollectionName=Essentialities"
      - "GeneMongoDbSettings:GeneProteinProductionCollectionName=ProteinProductions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayCollectionName=ProteinActivityAssays"
      - "GeneMongoDbSettings:GeneHypomorphCollectionName=Hypomorphs"
      - "GeneMongoDbSettings:GeneCrispriStrainCollectionName=CrispriStrains"
      - "GeneMongoDbSettings:GeneResistanceMutationCollectionName=ResistanceMutations"
      - "GeneMongoDbSettings:GeneVulnerabilityCollectionName=Vulnerabilities"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationCollectionName=UnpublishedStructuralInformations"
      - "GeneMongoDbSettings:GeneExpansionPropCollectionName=GeneExpansionProps"

      - "GeneMongoDbSettings:GeneRevisionCollectionName=GenesRevisions"
      - "GeneMongoDbSettings:StrainRevisionCollectionName=StrainsRevisions"
      - "GeneMongoDbSettings:GeneEssentialityRevisionCollectionName=EssentialitiesRevisions"
      - "GeneMongoDbSettings:GeneProteinProductionRevisionCollectionName=ProteinProductionsRevisions"
      - "GeneMongoDbSettings:GeneProteinActivityAssayRevisionCollectionName=ProteinActivityAssaysRevisions"
      - "GeneMongoDbSettings:GeneHypomorphRevisionCollectionName=HypomorphsRevisions"
      - "GeneMongoDbSettings:GeneCrispriStrainRevisionCollectionName=CrispriStrainsRevisions"
      - "GeneMongoDbSettings:GeneResistanceMutationRevisionCollectionName=ResistanceMutationsRevisions"
      - "GeneMongoDbSettings:GeneVulnerabilityRevisionCollectionName=VulnerabilitiesRevisions"
      - "GeneMongoDbSettings:GeneUnpublishedStructuralInformationRevisionCollectionName=UnpublishedStructuralInformationsRevisions"
      - "GeneMongoDbSettings:ExpansionPropRevisionCollectionName=GeneExpansionPropsRevisions"

    ports:
      - "8001:80"

  Target.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

       ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=target-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - TargetMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "TargetMongoDbSettings:DatabaseName=Target"
      - "TargetMongoDbSettings:TargetCollectionName=Targets"
      - "TargetMongoDbSettings:PromotionResponseCollectionName=PromotionResponses"
      - "TargetMongoDbSettings:TargetRevisionCollectionName=TargetsRevisions"

    ports:
      - "8002:80"

  Screen.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}

      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=screen-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"


      ## MongoDb Data Store
      - ScreenMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "ScreenMongoDbSettings:DatabaseName=Screen"

      - "ScreenMongoDbSettings:ScreenCollectionName=Screens"
      - "ScreenMongoDbSettings:ScreenRunCollectionName=ScreenRuns"
      - "ScreenMongoDbSettings:HitCollectionCollectionName=HitCollections"
      - "ScreenMongoDbSettings:HitCollectionName=Hits"

      - "ScreenMongoDbSettings:ScreenRevisionCollectionName=ScreensRevisions"
      - "ScreenMongoDbSettings:ScreenRunRevisionCollectionName=ScreenRunsRevisions"
      - "ScreenMongoDbSettings:HitCollectionRevisionCollectionName=HitCollectionsRevisions"
      - "ScreenMongoDbSettings:HitRevisionCollectionName=HitRevisions"

      ## Internal APIs
      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8003:80"

  HitAssessment.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=hitassessment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - HAMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "HAMongoDbSettings:DatabaseName=HitAssessment"

      - "HAMongoDbSettings:HitAssessmentCollectionName=HitAssessments"
      - "HAMongoDbSettings:HaCompoundEvolutionCollectionName=HaCompoundEvolutions"

      - "HAMongoDbSettings:HitAssessmentRevisionCollectionName=HitAssessmentsRevisions"
      - "HAMongoDbSettings:HaCompoundEvolutionRevisionCollectionName=HaCompoundEvolutionsRevisions"

      ## Internal APIs
      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8004:80"

  Project.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=project-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - ProjectMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "ProjectMongoDbSettings:DatabaseName=Project"

      - "ProjectMongoDbSettings:ProjectCollectionName=Projects"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionCollectionName=ProjectCompoundEvolutions"

      - "ProjectMongoDbSettings:ProjectRevisionCollectionName=ProjectsRevisions"
      - "ProjectMongoDbSettings:ProjectCompoundEvolutionRevisionCollectionName=ProjectCompoundEvolutionsRevisions"
      
      ## Internal APIs
      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8005:80"

  Horizon.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      # Neo4j
      - HorizonNeo4jSettings:Uri=${HorizonNeo4jURI}
      - HorizonNeo4jSettings:User=${HorizonNeo4jUser}
      - HorizonNeo4jSettings:Password=${HorizonNeo4jPassword}
      - "HorizonNeo4jSettings:Database=horizon"
    
      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=horizon-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

    ports:
      - "8006:80"

  MLogix.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      # Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      # Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      # Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=mlogix-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      # MongoDb Data Store
      - MLxMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "MLxMongoDbSettings:DatabaseName=MoleculeLogix"
      - "MLxMongoDbSettings:MoleculeCollectionName=Molecules"
      - "MLxMongoDbSettings:MoleculeRevisionCollectionName=MoleculesRevisions"

      # Internal APIs
      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"

    ports:
      - "8007:80"

  Questionnaire.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Data Store
      - QuestionnaireMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}
      - "QuestionnaireMongoDbSettings:DatabaseName=Questionnaire"

    ports:
      - "8008:80"

  Comment.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## Event Store
      - EventDatabaseSettings:ConnectionString=${EventDB_ConnectionString}
      - "EventDatabaseSettings:DatabaseName=DaikonEventStore"
      - "EventDatabaseSettings:CollectionName=Events"

      ## Kafka Producer
      - KafkaProducerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaProducerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaProducerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaProducerSettings:Topic=${KafkaTopic}

      ## Kafka Consumer
      - KafkaConsumerSettings:BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings:ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings:SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings:Topics=${KafkaConsumerTopics}

      - "KafkaConsumerSettings:GroupId=comment-consumer-group"
      - "KafkaConsumerSettings:AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings:EnableAutoCommit=true"
      - "KafkaConsumerSettings:AllowAutoCreateTopics=true"

      ## MongoDb Data Store
      - CommentMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "CommentMongoDbSettings:DatabaseName=Comments"

      - "CommentMongoDbSettings:CommentCollectionName=Comments"
      - "CommentMongoDbSettings:CommentRevisionCollectionName=CommentsRevisions"

      - "CommentMongoDbSettings:CommentReplyCollectionName=CommentReplies"
      - "CommentMongoDbSettings:CommentReplyRevisionCollectionName=CommentReplyRevisions"

      ## Internal APIs
      - "MolDbAPI:Url=http://MolDb.API/api/v2/mol-db"
      - "MLogixAPI:Url=http://MLogix.API/api/v2"

    ports:
      - "8009:80"

  UserStore.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## MongoDb Data Store
      - UserStoreMongoDbSettings:ConnectionString=${MongoDB_ConnectionString}

      - "UserStoreMongoDbSettings:DatabaseName=UserStore"

      - "UserStoreMongoDbSettings:AppOrgCollectionName=AppOrgs"
      - "UserStoreMongoDbSettings:AppUserCollectionName=AppUsers"
      - "UserStoreMongoDbSettings:AppRoleCollectionName=AppRoles"
      - "UserStoreMongoDbSettings:APIResourceCollectionName=AppAPIResources"
    ports:
      - "8011:80"

  # Ocelotapigw:
  #   container_name: ocelotapigw
  #   environment:
  #     - "ASPNETCORE_ENVIRONMENT=Cluster"
  #     - ASPNETCORE_URLS=http://+:80
  #     - "UserStoreAPI:BaseUrl=http://UserStore.API/api/v2/"
  #   ports:
  #     - "8010:80"

  SimpleGW.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      ## OIDC
      - OIDCProvider=EntraID
      - EntraID:Instance=${EntraID_Instance}
      - EntraID:Domain=${EntraID_Domain}
      - EntraID:TenantId=${EntraID_TenantId}
      - EntraID:ClientId=${EntraID_ClientId}
      - EntraID:Audience=${EntraID_Audience}

      ## Internal API Routing
      - "UserStoreAPI:BaseUrl=http://UserStore.API/api/v2/"

      - "EndPointRouting:gene=http://Gene.API"
      - "EndPointRouting:gene-batch=http://Gene.API"
      - "EndPointRouting:strain=http://Gene.API"

      - "EndPointRouting:target=http://Target.API"
      - "EndPointRouting:screen=http://Screen.API"
      - "EndPointRouting:hit-collection=http://Screen.API"

      - "EndPointRouting:hit-assessment=http://HitAssessment.API"
      - "EndPointRouting:project=http://Project.API"
      - "EndPointRouting:horizon=http://Horizon.API"
      - "EndPointRouting:molecule=http://MLogix.API"
      - "EndPointRouting:api-resources=http://UserStore.API"
      - "EndPointRouting:app-settings=http://UserStore.API"
      - "EndPointRouting:org=http://UserStore.API"
      - "EndPointRouting:roles=http://UserStore.API"
      - "EndPointRouting:user=http://UserStore.API"
      - "EndPointRouting:questionnaire=http://Questionnaire.API"
      - "EndPointRouting:comment=http://Comment.API"
      - "EndPointRouting:mol-db=http://MolDb.API"

    ports:
      - "8010:80"

  MolDb.API:
    environment:
      
      # MolDb Postgres
      - MolDbUser=${MolDbUser}
      - MolDbPassword=${MolDbPassword}
      - MolDbHost=${MolDbHost}
      - MolDbPort=${MolDbPort}
      - MolDbDatabase=${MolDbDatabase}

      # Kafka Consumer
      - KafkaConsumerSettings_BootstrapServers=${KafkaBootstrapServers}
      - KafkaConsumerSettings_ConnectionString=${KafkaConnectionString}
      - KafkaConsumerSettings_SecurityProtocol=${KafkaSecurityProtocol}
      - KafkaConsumerSettings_Topics=${KafkaConsumerTopics}
      - "KafkaConsumerSettings_GroupId=moldb-consumer-group"
      - "KafkaConsumerSettings_AutoOffsetReset=Earliest"
      - "KafkaConsumerSettings_EnableAutoCommit=true"
      - "KafkaConsumerSettings_AllowAutoCreateTopics=true"

    ports:
      - "8101:80"